eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    A-a:
      path: /A-a/**
      serviceId: service-ribbon
    B-b:
      path: /B-b/**
      serviceId: service-feign