server:
  port: 8763

spring:
  application:
    name: service-hi
  cloud:
    config:
      profile: dev
      label: master
      uri: http://localhost:8888/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/